# Generated by Django 4.1.7 on 2023-04-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compounds',
            fields=[
                ('compound_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molecular_formula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solvents',
            fields=[
                ('solvent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('spectrum_id', models.AutoField(primary_key=True, serialize=False)),
                ('formated', models.TextField()),
                ('compound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.compounds')),
                ('solvent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solvents')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Peaks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peak_ppm', models.FloatField()),
                ('integral_area', models.FloatField()),
                ('spektrum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.spectrum')),
            ],
        ),
        migrations.CreateModel(
            name='Impurities',
            fields=[
                ('impurity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('solvent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solvents')),
            ],
        ),
    ]
