# Generated by Django 4.2 on 2023-04-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molecular_formula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formated', models.TextField()),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.compound')),
                ('solvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'unique_together': {('user', 'solvent', 'compound', 'formated')},
            },
        ),
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ppm', models.FloatField()),
                ('integral_area', models.FloatField()),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.spectrum')),
            ],
        ),
        migrations.CreateModel(
            name='Impurity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('solvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solvent')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spectrum1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons1', to='main.spectrum')),
                ('spectrum2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons2', to='main.spectrum')),
            ],
        ),
    ]
