# Generated by Django 4.2 on 2023-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
