# Generated by Django 4.1.7 on 2023-04-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compounds',
            old_name='compound_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='impurities',
            old_name='impurity_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='solvents',
            old_name='solvent_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='spectrum',
            old_name='spectrum_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
