# Generated by Django 4.2 on 2023-04-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_spectrum_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvent',
            name='position',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
