# Generated by Django 4.1.7 on 2023-04-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_compounds_compound_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Impuritie',
            new_name='Impurity',
        ),
    ]
