# Generated by Django 4.2 on 2023-05-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_solvent_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spectrum',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='spectrum1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons1', to='main.spectrum'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='spectrum2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons2', to='main.spectrum'),
        ),
        migrations.AlterField(
            model_name='impurity',
            name='solvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.solvent'),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='compound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.compound'),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='solvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.solvent'),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
    ]
