# Generated by Django 4.1.7 on 2023-04-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_impuritie_impurity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spectrum',
            unique_together={('user', 'solvent', 'compound', 'formated')},
        ),
    ]
