# Generated by Django 4.2 on 2023-05-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_spectrum_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
