# Generated by Django 4.1.7 on 2023-04-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_spectrum_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peak',
            old_name='spektrum',
            new_name='spectrum',
        ),
    ]
