# Generated by Django 4.1.7 on 2023-04-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_spektrum_peak_spectrum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spectrum1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons1', to='main.spectrum')),
                ('spectrum2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons2', to='main.spectrum')),
            ],
            options={
                'unique_together': {('spectrum1', 'spectrum2')},
            },
        ),
    ]
